<?php
// $Id: userpoints_reset.module,v 1.1 2006-09-17 03:10:04 kbahey Exp $

define(USERPOINTS_PERM_RESET, 'reset userpoints');

function userpoints_reset_help($section) {
  switch ($section) {
    case 'admin/modules#description':
    case 'admin/settings/userpoints_reset':
      $output = t('Reset userpoints');
      break;
  }
  return $output;
}

function userpoints_reset_menu($may_cache) {
  $items = array();

  $items[] = array(
    'path'     => 'userpoints_reset',
    'callback' => 'userpoints_reset_confirm',
    'title'    => t('reset userpoints'),
    'access'   => user_access(USERPOINTS_PERM_RESET),
    'type'     => MENU_NORMAL_ITEM);

   return $items;
}

function userpoints_reset_perm() {
  return array (USERPOINTS_PERM_RESET);
}

function userpoints_reset_confirm() {
  $form['confirm'] = array(
    '#type' => 'textfield',
    '#title' => t('Reset all userpoints. This is useful in certain situations such as monthly contests. Enter YES without quotes to reset'),
    '#size' => 3,
    '#maxlength' => 3,
    '#default_value' => t('NO'));

  $form['reset'] = array(
    '#type' => 'submit',
    '#value' => t('Reset'));

  return drupal_get_form('userpoints_reset', $form);
}

function userpoints_reset_submit($form_id, $edit) {
  if ($edit['confirm'] == t('YES')) {
    db_query('DELETE FROM {userpoints}');
    drupal_set_message(t('All userpoints have been reset!'));
  }
}
