<?php

//$Id: userpoints_autoapprove.module,v 1.1 2007-05-29 03:59:29 kbahey Exp $

define('USERPOINTS_AUTOAPPROVE_PERIOD', 'userpoints_autoapprove_period');

function userpoints_autoapprove_help($section) {
  switch ($section) {
    case 'admin/settings/userpoints_autoapprove':
      $output = t('Provides extra reporting on transactions.');
      break;
  }
  return $output;
}

function userpoints_autoapprove_userpoints($op, $points = 0, $uid = 0, $event = '') {
  switch($op) {
    case 'setting':
      $form['autoapprove'] = array(
        '#type' => 'fieldset',
        '#title' => t('Autoapprove Settings'),
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
      );

      $form['autoapprove'][USERPOINTS_AUTOAPPROVE_PERIOD] = array(
        '#type' => 'textfield',
        '#title' => t('Time (in hours), after which !Points will automatically be approved (<0 inactivates)', userpoints_translation()),
        '#default_value' => variable_get(USERPOINTS_AUTOAPPROVE_PERIOD, 0),
        '#size' => 10,
        '#maxlength' => 8,
      );

    return $form;
  }
}

function userpoints_autoapprove_cron() {
  if (variable_get(USERPOINTS_AUTOAPPROVE_PERIOD, 0) > 0) {
    $result = db_query("SELECT txn_id, uid, points, event, description FROM {userpoints_txn} WHERE time_stamp < %d AND status = 1", (time() - (variable_get(USERPOINTS_AUTOAPPROVE_PERIOD, 0) * 60 *60)));
    while ($row = db_fetch_object($result)) {
      userpoints_userpointsapi('txn approve', $row->points, $row->uid, $row->event, $row->description);
      db_query("UPDATE {userpoints_txn} SET status = %d, approver_uid = %d WHERE txn_id = %d", 0, 0, $row->txn_id);
    }
  }
}
