<?php

//$Id: userpoints_invite.module,v 1.3 2007-05-14 18:25:37 kbahey Exp $

// Copyright 2005-2007 Khalid Baheyeldin http://2bits.com

define('USERPOINTS_INVITE_INVITE',       'userpoints_invite_invite');
define('USERPOINTS_INVITE_REGISTER',     'userpoints_invite_register');

function userpoints_invite_help($section) {
  switch ($section) {
    case 'admin/settings/userpoints_basic':
      $output = t('<strong>UP:</strong> A userpoints interface with the invite module.');
      break;
  }
  return $output;
}

function userpoints_invite_userpoints($op, $points = 0, $uid = 0, $event = '') {
  switch($op) {
    case 'setting':
      $group = 'invite';
      $form[$group] = array(
        '#type'        => 'fieldset',
        '#collapsible' => TRUE,
        '#collapsed'   => TRUE,
        '#title'       => t('!Points for invite', userpoints_translation()),
      );
      
      $form[$group][USERPOINTS_INVITE_INVITE] = array(
        '#type'          => 'textfield',
        '#title'         => t('!Points for inviting a user (requires the invite module)', userpoints_translation()),
        '#default_value' => variable_get(USERPOINTS_INVITE_INVITE, 0),
        '#size'          => 5,
        '#maxlength'     => 5,
      );
    
      $form[$group][USERPOINTS_INVITE_REGISTER] = array(
        '#type'          => 'textfield',
        '#title'         => t('!Points when invited user registers (requires the invite module)', userpoints_translation()),
        '#default_value' => variable_get(USERPOINTS_INVITE_REGISTER, 0),
        '#size'          => 5,
        '#maxlength'     => 5,
      );
      return $form;
      break;
  }
}

function userpoints_invite($op, $args) {
  switch($op) {
    case 'invite':
      $points = variable_get(USERPOINTS_INVITE_INVITE, 0);
      break;
    case 'cancel':
      $points = -variable_get(USERPOINTS_INVITE_INVITE, 0);
      break;
    case 'escalate':
      $points = variable_get(USERPOINTS_INVITE_REGISTER, 0);
      $op = 'register';
      break;
  }
  userpoints_userpointsapi('points', $points, $args['inviter']->uid, 'invite '.$op);
}

