<?php

/**
 * @file
 * Userpoints Cap module for Drupal 5.x
 * Limit the number of points a user can earn.
 * @author Mike Smullin (http://www.mikesmullin.com)
 * @license GNU General Public License (http://www.gnu.org/copyleft/gpl.html)
 */

define('USERPOINTS_CAP_MAXIMUM', 'userpoints_cap_maximum');
define('USERPOINTS_CAP_MAXIMUM_DEFAULT', 1000000);

function userpoints_cap_userpoints($op, $new_points = 0, $uid = 0, $event = '') {
  switch($op) {
    case 'setting':
      $group = 'userpoints_cap';
      $form[$group] = array(
        '#type' => 'fieldset',
        '#title' => t('!Points Cap', userpoints_translation()),
        '#description' =>  t('Maximum number of !points allowed for each user.', userpoints_translation()),
        '#collapsible' => TRUE,
        '#collapsed' => TRUE,
      );

      $form[$group][USERPOINTS_CAP_MAXIMUM] = array(
        '#type' => 'textfield',
        '#title' => t('Maximum !Points per User', userpoints_translation()),
        '#default_value' => variable_get(USERPOINTS_CAP_MAXIMUM, USERPOINTS_CAP_MAXIMUM_DEFAULT),
      );

      return $form;
      break;

    case 'points before':
      $current_points = userpoints_get_current_points($uid);
      $max_points = variable_get(USERPOINTS_CAP_MAXIMUM, USERPOINTS_CAP_MAXIMUM_DEFAULT);
      if ($current_points + $new_points > $max_points) {
        drupal_set_message(t('!Points are limited to a maximum; you must spend to earn more.', userpoints_translation()));
        return FALSE; // DO NOT add points
      } else return TRUE; // OK to add points
      break;
  }
}