<?php
// $Id: userpoints_reset.module,v 1.2 2007-06-29 22:14:38 kbahey Exp $

define(USERPOINTS_PERM_RESET, 'reset userpoints');

function userpoints_reset_help($section) {
  switch ($section) {
    case 'admin/settings/userpoints/reset':
      $output = t('Reset userpoints');
      break;
  }
  return $output;
}

function userpoints_reset_menu($may_cache) {
  $items = array();

  $items[] = array(
    'path'     => 'admin/settings/userpoints/reset',
    'callback' => 'userpoints_reset_page',
    'title'    => t('Reset'),
    'access'   => user_access(USERPOINTS_PERM_RESET),
    'type'     => MENU_NORMAL_ITEM);

   return $items;
}

function userpoints_reset_perm() {
  return array (USERPOINTS_PERM_RESET);
}

function userpoints_reset_page() {
  return drupal_get_form('userpoints_reset', $form);
}

function userpoints_reset() {
  $form = array();

  $form['confirm'] = array(
    '#type' => 'textfield',
    '#title' => t('Reset all userpoints. This is useful in certain situations such as monthly contests. Enter YES to reset'),
    '#size' => 3,
    '#maxlength' => 3,
    '#default_value' => t('NO'));

  $form['reset'] = array(
    '#type' => 'submit',
    '#value' => t('Reset'));

  return $form;
}
function userpoints_reset_submit($form_id, $edit) {
  if ($edit['confirm'] == t('YES')) {
    userpoints_reset_do();
    drupal_set_message(t('All userpoints have been reset!'));
    drupal_goto('admin/settings/userpoints');
  }
}

function userpoints_reset_do() {
  db_query('DELETE FROM {userpoints}');
}
